### ISSUE TITLE
Doesn't really work with Tabs-Plugin & Safari

### ISSUE THREAD

**Issue by wottpal** [medienbaecker/kirby-simplemde#10]
Hi,
I finally found some time to try out your nice editor. I really like it so far but can't use it in production right now because of this issue. (Actually I'm not sure if it's an issue with your plugin of with the tabs-plugin.)

If I have tabs enabled (with https://github.com/afbora/Kirby-Tabs-Field) like:

```yaml
  tab:
    label: Allgemein
    type:  tabs

  text:
    label: Text
    type: simplemde
```

The editor looks like this:
<img width="690" alt="screen shot 2018-01-05 at 13 41 18" src="https://user-images.githubusercontent.com/3930150/34609825-8b81f38c-f21e-11e7-86a5-76c86e06eddf.png">

If I remove the tab-definition everything works fine in Safari. In Chrome everything works fine even with the tabs-definition.

Thanks!
Dennis
